name: Test deployment

on:
  pull_request:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@5
        with:
          node-version: 22
          cache: yarn

      - name: install dependency packages
        run: sudo apt install -y doxygen
      - name: set up site
        run: |
          git clone https://github.com/yourWaifu/sleepy-discord.git
          cd sleepy-discord
          git checkout develop

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: |
          npx tsc --p reference-generator-tsconfig.json
          yarn build

