name: Test deployment

on:
  pull_request:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: install dependency packages
        run: sudo apt install -y doxygen
      - name: set up site
        run: |
          git clone https://github.com/yourWaifu/sleepy-discord.git
          cd sleepy-discord
          git checkout develop
          cp ../Doxyfile ./
          echo "Run Doxygen"
          doxygen
          echo "Move Doxygen Files"
          mkdir ../xml
          mv xml/* ../xml
          echo "Download Doxybook2"
          cd ..
          curl -o doxybook2.zip -LO "https://github.com/matusnovak/doxybook2/releases/download/v1.4.0/doxybook2-linux-amd64-v1.4.0.zip"
          unzip -j "doxybook2.zip" "bin/doxybook2" -d "."
          echo "Run Doxybook2"
          mkdir docs/reference
          ./doxybook2 --input ./xml --output ./docs/reference --config ./doxybook.config.json --templates templates/

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: |
          npx tsc --p reference-generator-tsconfig.json
          yarn build

